os:
- linux
- osx
language: cpp
before_script: autoreconf --force --install
script: mkdir build && ./configure --prefix=`pwd`/build && make install
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh deploy.sh
  on:
    repo: VitensTC/VIPhreeqc

env:
  global:
    secure: WGMo55FW7arAz7eFWpyqd83PI+vohzU89KQcX0ufRML8tDJEe8E6dWCGMDu8ZR276A2WquylAp25oRoCRm8ZSw6rAJA0Po7+GTZ3v5mRVH30XzLvX3eJWRQP2oNbn2FRJ1U0rXKcxCuDsPe3aoJllXuiyp7adKXtW9Ce9aORevuWPJtSvSAau1x3gLhhfs7AIst5Nb4WoRT1nRZiQuM4qku2GEI/WzqxSIDg/odzNrCjvp7BtiDwwuuTkgF0sAX2Glsph0otTiilKCmasZUTKT9ZI0OTfUivBwMCKG1fq+QU3rL0oLS1nzySF/SrfISYwLm+I5i236bUlLj8CgLD9u0h/tltbnj2NSXcMoPwOJ2vnBG6wA/7kzizjK02s1Ak4BSYvBGaIDmSGaRRl03iVXJXOUfVTaikKoozFXLAS7y3WB8kRQDrS05hNN8H8HTxmgEfsUKEb1ieySOMURU5AKJAs+C5z7X8QIkngAL/MvDgwkPYG7NBBg/j9Vv526wdCp1YJOJXS/pZlRwXYhCeq8L/KDBI2WXB0FqW5x8N/TcNZrVMW1740OTDpIfpAYPe6l0jIs0ZQ3vfD7pyhn3fNqQXw3zd0uH8moBBDy3qiln2YM03pAEgRT6bXSJ6MoQ+aiEIXvJPPDOZ+U+wyHeEOvkvXRKPCF9m+m9p7oUwwQ8=
