image: Visual Studio 2015
platform: x86
configuration: Release

environment:
  token:
    secure: QECCMgb2aMisxefvyRQI+5x9AgU0GaVINxob8E/xY6KW9yH4VFoyWo43VSOph7dc

build_script:
  - cd C:/projects/viphreeqc
  - cmake -DBUILD_SHARED_LIBS:BOOL=ON -G "Visual Studio 14 2015" .
  - cmake --build . --config Release

after_build:
  - cd C:/projects/viphreeqc/release
  - dir
